import { Currency } from "../types";

export const DUMMY_RESPONSE: Array<Currency> = [
  {
    country: "Australia",
    currency: "dollar",
    amount: 1,
    code: "AUD",
    rate: 14.995,
  },
  { country: "Brazil", currency: "real", amount: 1, code: "BRL", rate: 4.606 },
  {
    country: "Bulgaria",
    currency: "lev",
    amount: 1,
    code: "BGN",
    rate: 12.661,
  },
  {
    country: "Canada",
    currency: "dollar",
    amount: 1,
    code: "CAD",
    rate: 16.941,
  },
  {
    country: "China",
    currency: "renminbi",
    amount: 1,
    code: "CNY",
    rate: 3.162,
  },
  {
    country: "Czech Republic",
    currency: "czech koruna",
    amount: 1,
    code: "CZK",
    rate: 1,
  },
  { country: "Denmark", currency: "krone", amount: 1, code: "DKK", rate: 3.32 },
  { country: "EMU", currency: "euro", amount: 1, code: "EUR", rate: 24.765 },
  {
    country: "Hongkong",
    currency: "dollar",
    amount: 1,
    code: "HKD",
    rate: 2.91,
  },
  {
    country: "Hungary",
    currency: "forint",
    amount: 100,
    code: "HUF",
    rate: 6.454,
  },
  {
    country: "Iceland",
    currency: "krona",
    amount: 100,
    code: "ISK",
    rate: 16.654,
  },
  { country: "IMF", currency: "SDR", amount: 1, code: "XDR", rate: 30.284 },
  {
    country: "India",
    currency: "rupee",
    amount: 100,
    code: "INR",
    rate: 27.366,
  },
  {
    country: "Indonesia",
    currency: "rupiah",
    amount: 1000,
    code: "IDR",
    rate: 1.455,
  },
  {
    country: "Israel",
    currency: "new shekel",
    amount: 1,
    code: "ILS",
    rate: 6.041,
  },
  { country: "Japan", currency: "yen", amount: 100, code: "JPY", rate: 15.387 },
  {
    country: "Malaysia",
    currency: "ringgit",
    amount: 1,
    code: "MYR",
    rate: 4.813,
  },
  { country: "Mexico", currency: "peso", amount: 1, code: "MXN", rate: 1.333 },
  {
    country: "New Zealand",
    currency: "dollar",
    amount: 1,
    code: "NZD",
    rate: 13.917,
  },
  { country: "Norway", currency: "krone", amount: 1, code: "NOK", rate: 2.164 },
  {
    country: "Philippines",
    currency: "peso",
    amount: 100,
    code: "PHP",
    rate: 40.433,
  },
  { country: "Poland", currency: "zloty", amount: 1, code: "PLN", rate: 5.675 },
  { country: "Romania", currency: "leu", amount: 1, code: "RON", rate: 4.975 },
  {
    country: "Singapore",
    currency: "dollar",
    amount: 1,
    code: "SGD",
    rate: 16.96,
  },
  {
    country: "South Africa",
    currency: "rand",
    amount: 1,
    code: "ZAR",
    rate: 1.186,
  },
  {
    country: "South Korea",
    currency: "won",
    amount: 100,
    code: "KRW",
    rate: 1.698,
  },
  { country: "Sweden", currency: "krona", amount: 1, code: "SEK", rate: 2.18 },
  {
    country: "Switzerland",
    currency: "franc",
    amount: 1,
    code: "CHF",
    rate: 26.188,
  },
  {
    country: "Thailand",
    currency: "baht",
    amount: 100,
    code: "THB",
    rate: 63.844,
  },
  {
    country: "Turkey",
    currency: "lira",
    amount: 100,
    code: "TRY",
    rate: 75.223,
  },
  {
    country: "United Kingdom",
    currency: "pound",
    amount: 1,
    code: "GBP",
    rate: 28.937,
  },
  { country: "USA", currency: "dollar", amount: 1, code: "USD", rate: 22.749 },
];
